# Generated by Django 5.2.5 on 2025-09-03 19:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
            ],
            options={
                "ordering": ["name", "model"],
            },
        ),
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail", "Розничная сеть"),
                            ("sole", "ИП"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(db_index=True, max_length=100)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("street", models.CharField(max_length=150)),
                ("house_number", models.CharField(max_length=30)),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to="network.networknode",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="nodes", to="network.product"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["country", "city"],
                        name="network_net_country_e3d63f_idx",
                    )
                ],
            },
        ),
    ]
