server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/    { proxy_pass http://web:8000/api/; }
    location /admin/  { proxy_pass http://web:8000/admin/; }
    location /swagger/ { proxy_pass http://web:8000/swagger/; }
    location /redoc/   { proxy_pass http://web:8000/redoc/; }
    location /health   { proxy_pass http://web:8000/health; }
}
